 const projects = [
  {
    title: "weTravelToo",
    description: "MERN stack App, using graphql, and Cloudinary",
    line: "A Travel blog for users to take about traviling. You can login post, create blog andupload your images",
    img: require("../../assets/photos/"),
    alt: "A blog Screenshots",
    website: "...",
    repo: "...",
  },
  {
    title: "Sunny-SideUp",
    description: "Javascript, Rest-API, and googl's maps API  ",
    line: "weather app foucusing on current activinies, weather, and alarts around the sure.",
    img: require("../../assets/photos/"),
    alt: "Sunny-SideUp Screenshots",
    website:
      "",
    repo: "",
  },

  {
    title: "password generator",
    description: "Javascript, CSS, HtMl",
    line: "",
    img: require("../../assets/photos/password-generator.png"),
    alt: "PassWord Generator Screenshots",
    website: "",
    repo: "",
  },

  {
    title: "",
    description: "",
    line: "",
    img: require("../../assets/photos/"),
    alt: "...Screenshots  ",
    website: "https://LastSlice.org",
    repo: "https://LastSlice.org",
  },

  {
    title: "i-Reckon",
    description: "HTML, CSS, Javascript, Weather API",
    line: "An app to get local weather reports. or search by city name. Automaticly it saves the cities you look up. You can clear history if you wish.",
    img: require("../../assets/photos/"),
    alt: "Weather App Screenshots",
    website: "",
    repo: "",
  },
  {
    title: "budget Tracker",
    description: "Node js applecation",
    line: "My first portfolio page built after 4 weeks in class. How far I've come!",
    img: require("../../assets/photos/"),
    alt: "Budget tracker Screenshots",
    website: "",
    repo: "",
  },
  {
    title: "",
    description: "",
    line: "...",
    img: require("../../assets/photos/"),
    alt: "Screenshots ",
    website: "",
    repo: "",
  },
  {
    title: "Quizky",
    description: "HTML, CSS, Javascript",
    line: "A fun quiz to test your JS Knowlag",
    img: require("../../assets/photos/quizPic.png"),
    alt: "Quizky Screenshots",
    website: " ",
    repo: "",
  },
];
